# fly.toml app configuration file generated for lunch-helper on 2023-06-13T16:51:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lunch-helper"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
